### ISSUE TITLE
Founder address in GBT

### ISSUE THREAD

**Issue by crackfoo** [CommerciumBlockchain/CommerciumContinuum#2]
Hi, 

Can you please add the founder address to the getblocktemplate? So then everyone know who exactly is getting paid:

```
    ],
    "fee": 0,
    "sigops": 2,
    "foundersreward": 60000000,
    "required": true
  },
```

**Comment by anthony19114** [comment]
There are three founders addresses.
 vFoundersRewardAddress = {
            "MZMN4YjaYhnnDgMWLQVC93LuCPFJ51tBwT", /* main-index: 0*/
            "MujoWRKHEy3ndn2V5JZrXhQSiy3huZPV8U", /* main-index: 1*/
            "MqdZ2ji6rX2HsBXdt9WpES2RSaE7R6A5zF", /* main-index: 2*/
};

The first one is done. There will be no more coins sent there.

The second one has activated. On block 176534
Every 176534 blocks, it changes.. but there is only 1 more change and then there is no founders reward after block 529602. So the next change on block 353068 swap it to MqdZ2ji6rX2HsBXdt9WpES2RSaE7R6A5zF

I am not convinced that the founders reward should be part of gbt or gbs. Technically pay the next and last founders address at block 353068 and its done. I understand the lack of documentation on this started an issue. I believe this "GitHub Issues" will be a reference to current and future pool operators on the functionality of founders rewards.
